Hadia/view binding project activity view holder
kickstarter/android-oss pull request #1088
Opened 2021-02-08 16:14 UTC by hadia

# 📲 What

Remove butter knife from view holder and replaced with view binding

# 🤔 Why
deprecated butterknife 

# 🛠 How

1- change view holder classes from java to kotlin
2- refactor adapters to create view holders with view group object rather than view object
3-remove butter-knife and replace it with viewbinding 

# 👀 See

https://kickstarter.atlassian.net/browse/NT-1731

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# 📋 QA

Test all recycled views for all views

2021-02-09 18:40 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/adapters/CreatorDashboardAdapter.java
> +  //ProjectContextViewHolder(ProjectContextViewBinding.inflate(LayoutInflater.from(viewGroup.getContext()), viewGroup, false)
Can be deleted

2021-02-09 23:59 UTC, Arkariang approved these changes
I left a few comments, but they are small things having in mind the size of this PR. Great work @hadia

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/viewholders/CommentViewHolder.kt
> +            } else if (CommentUtils.isUserAuthor(comment, currentUser.user)) {
`currentUser.user` is deprecated
you should subscribe to the `environment().currentUser().observable()` in order to get the current user

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardHeaderViewHolder.kt
> +    fun projectsListButtonClicked() {
this 3 button clicked functions can be private

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/viewholders/DiscoveryOnboardingViewHolder.kt
> +    fun loginToutClick() {
can be private

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/res/layout/project_tags.xml
> +    android:id="@+id/project_tags"
identation here

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/res/layout/project_media_header.xml
> +<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
We try to just use ConstraintLayout in order to build UI if that's possible.

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/res/layout/project_card_view.xml
> +        <include
Identation for all the touched lines

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/res/layout/item_reward_selected_card.xml
> +      <include
Identation

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/res/layout-land/project_card_view.xml
> +            android:id="@+id/project_metadata_view"
Identation

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/TopFilterViewHolder.kt
> +        val textColor = if (item?.selected() == true) context.resources.getColor(R.color.accent, null)
I'm usually not picky with the syntax, as we do not have an automatic linter in place yet, but this is confusing to read as it is, could you change it to something like this? 
![Uploading Screen Shot 2021-02-09 at 3.38.44 PM.png…]()

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedOutViewHolder.kt
> +    fun activityClick() {
all this method could be private

2021-02-09 23:59 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/viewholders/ProjectUpdateViewHolder.kt
> +        if (project != null && user != null && photo != null && update != null) {
Thanks!! 🙏 , I remember this part having returns for each val in case of null!

2021-02-10 00:02 UTC, Arkariang requested changes
I'll mark as request change the use of the deprecated `currentUser.user`,  Trying to move away as much as possible from any deprecated code

2021-02-10 16:45 UTC, Arkariang approved these changes

2021-02-10 18:08 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/ui/viewholders/CommentViewHolder.kt
> +            Picasso.with(context).load(comment.author()?.avatar()?.small())
Since `small()` is `@Nullable`, we should be checking that this url is not null or else Picasso will cause the app to crash.

2021-02-10 18:13 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.kt
> +            .load(avatarUrl)
since `avatarUrl` is of type `String?` we should also be checking here if avatarUrl is null since this will cause a crash if that is the case.

2021-02-10 18:15 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/ui/viewholders/ProjectSocialViewHolder.kt
> +        Picasso.with(context()).load(user?.avatar()?.small())
Same comment about nullable urls and picasso

2021-02-10 18:17 UTC, leighdouglas requested changes
Requesting changes only because of the Picasso crashing the app possibility by passing null URLs. Otherwise looks great!! Fantastic job! 🎉 🎉

2021-02-10 19:18 UTC, leighdouglas approved these changes
Fantastic!! 🚀

2021-02-10 19:40 UTC, merged