NT-1776:Refactor SignupActivity
kickstarter/android-oss pull request #1103
Opened 2021-02-16 18:28 UTC by hadia

# 📲 What

Remove butter knife from SignupActivity and replaced with view binding

# 🤔 Why

deprecated butterknife

# 🛠 How

1- change SignupActivity from java to kotlin
3-remove butter-knife and replace it with viewbinding

# 👀 See

https://user-images.githubusercontent.com/1075310/108105578-79c00f00-7095-11eb-9368-3b8aad2eab4e.mp4
| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# 📋 QA
Open app try to sign up
# Story 📖

https://kickstarter.atlassian.net/browse/NT-1776

2021-02-17 22:32 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
> +        if (this.supportFragmentManager.backStackEntryCount == 0) {
this if condition can be deleted, it was mean to not allow pressing back button on the `Interstitial Fragment` that screen is no longer presented

2021-02-17 22:47 UTC, Arkariang requested changes
Apart from the override method everything else looks good, I've tested the signUp with errors scenarios and all works fine. As soon as that override method is deleted I'll approve it 
![SignUpErrorCase](https://user-images.githubusercontent.com/4083656/108277953-18e51500-712f-11eb-9382-06de14eaecd1.gif)

2021-02-17 22:47 UTC, Arkariang commented on app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
> +    override fun back() {
This override method can be deleted, it was meant to avoid pressing the back button on the `Interstitial Fragment` that is no longer used

2021-02-18 14:57 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
> +        viewModel.outputs.signupSuccess()
nit: whitespace after line 27

2021-02-18 14:58 UTC, leighdouglas approved these changes
LGTM once @Arkariang approves 🎉

2021-02-18 19:18 UTC, Arkariang approved these changes
Lgtm!

2021-02-18 20:39 UTC, merged