[MBL-1227] Add post campaign messaging for project page
kickstarter/android-oss pull request #1967
Opened 2024-03-04 21:33 UTC by mtgriego

# 📲 What

Add the new messaging for when a project is collecting post campaign pledges to the project page

# 🤔 Why

The people need to know

# 🛠 How

Added a new string (translations needed) and populated based on project flags

# 👀 See

![Screenshot_20240304-132659](https://github.com/kickstarter/android-oss/assets/7563288/dc9e4e61-d758-4498-9e91-cf51a8bdcd4c)

# 📋 QA

1) Go to successful projects to see if the correct messaging shows up (not post campaign collecting message)
2) On staging go to the Baconbaconbacon project and confirm this is showing up correctly

# Story 📖

[MBL-1227](https://kickstarter.atlassian.net/browse/MBL-1227)

[MBL-1227]: https://kickstarter.atlassian.net/browse/MBL-1227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-04 21:34 UTC, mtgriego commented
I also had to add the builder fields for these to be properly populated on the project page

2024-03-05 08:51 UTC, Arkariang commented on app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
> +                .filter { !(it.postCampaignPledgingEnabled() ?: false) && !(it.isInPostCampaignPledgingPhase() ?: false) }
Can we add tests on `ProjectOverviewViewModelTest` to make sure this newly added logic is covered?

2024-03-05 08:51 UTC, Arkariang requested changes
Test!

2024-03-05 18:33 UTC, Arkariang approved these changes

2024-03-05 20:25 UTC, merged