MBL-1475 Add backing details navigation
kickstarter/android-oss pull request #2064
Opened 2024-06-26 20:52 UTC by ycheng-kickstarter

# 📲 What
When tapping the project title and thumbnail area of the card, should open a webview that loads the backing details url

# 🤔 Why

# 🛠 How
PPO cards are currently not hooked up to a backend query, so instead added a backingDetailsUrl field to the `PPOCardDataMock` data object 
When user clicks the backing summary, open webview with that test url

# 👀 See
Hamburger menu -> Alerts -> Click on 
https://github.com/kickstarter/android-oss/assets/129205442/a46b9b39-2d74-4937-b807-5f047c0cde82

# 📋 QA
To get PPO cards to show up, on line 15 of the VM, replace
`private val ppoCards = MutableStateFlow<PagingData<PPOCardDataMock>>(PagingData.empty())`
with mock data:
`private val ppoCards = MutableStateFlow<PagingData<PPOCardDataMock>>( PagingData.from( listOf( PPOCardDataMock(shippingAddress = "Firsty Lasty\n123 First St Apt #5678\nLos Angeles, CA 90025-1234\nUnited States", viewType = PPOCardViewType.CONFIRM_ADDRESS) ) ) )`

# Story 📖
https://kickstarter.atlassian.net/browse/MBL-1475

2024-06-26 20:58 UTC, ycheng-kickstarter commented on app/src/main/res/values/strings.xml
> +  <string name="address_confirmed_snackbar_text_fpo">Address confirmed! Need to change your address before it locks? Visit your backing details on our website.</string>
I snuck in this tiny string name change unrelated to this ticket because I realized I forgot to add "fpo" to the end of it

2024-06-27 15:58 UTC, ycheng-kickstarter commented on app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
> +    onProjectPledgeSummaryClick: (backingDetailsUrl: String) -> Unit,
Added a new `onProjectPledgeSummaryClick` lambda for just the pledge summary tap area per the ticket AC. The `onCardClick` lambda is for the tap area of the entire card, not sure if it's going to end up being used?

2024-06-27 17:06 UTC, mtgriego requested changes
Overall pretty good, though we should not be using RX2 in new viewmodels unless necessary for backwards compatibility etc

2024-06-27 17:06 UTC, mtgriego commented on app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/BackingDetailsActivity.kt
> +            .addToDisposable(disposables)
RX2 should be removed from here as well

2024-06-27 17:48 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/viewmodels/BackingDetailsViewModel.kt
> +        }
Agree with Matthew about not using rxjava. Also, the URL should come from the PPOCard, passed back to the view model when the click happens.

2024-06-27 18:07 UTC, ycheng-kickstarter commented on app/src/main/java/com/kickstarter/viewmodels/BackingDetailsViewModel.kt
> +        }
@leighdouglas The url does come from the PPOCard. When the click happens we open the BackingDetailsActivity and pass that url as an extra in the intent.

2024-06-27 18:08 UTC, ycheng-kickstarter commented on app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
> +                            onProjectPledgeSummaryClick = { onProjectPledgeSummaryClick(it.backingDetailsUrl) },
@leighdouglas Here's where we pass the backingDetailsUrl from the PPO card when user clicks on the tap area.

2024-06-27 18:09 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/viewmodels/BackingDetailsViewModel.kt
> +        }
Ah, gotcha. I misread, thanks!

2024-06-27 19:50 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/BackingDetailsActivity.kt
> +                viewModel.url.collect { url ->
🎉

2024-06-27 21:40 UTC, leighdouglas submitted a review, later dismissed
lgtm! 🎉

2024-06-27 23:33 UTC, mtgriego requested changes
LIttle more RX2 to remove

2024-06-27 23:33 UTC, mtgriego commented on app/src/main/java/com/kickstarter/viewmodels/BackingDetailsViewModel.kt
> +    private fun intent() = this.intent?.let { Observable.just(it) } ?: Observable.empty()
RX2 Observable still being used here

2024-07-01 16:08 UTC, mtgriego approved these changes

2024-07-01 16:36 UTC, merged