[NT-1453][NT-1344][NT-1399]: Fix Pledge with Digital addOns
kickstarter/android-oss pull request #974
Opened 2020-09-08 15:51 UTC by Arkariang

# 📲 What

- Pledge to a Digital Reward with Digital AddOns

# 🛠 How

- Refactor in PledgeFragmentViewModel
- Extracted shipping cost (Reward || Reward + AddOns)
- Extracted pledgeAmount ( Reward || Rewards + AddOns || NoReward )
- Extracted cost for DigitalReward
- Updated MaxPledge -> MaxPerProject - current pledgeAmount

# 👀 See

![PledgeDigitalAddOns](https://user-images.githubusercontent.com/4083656/92498558-a18a7d00-f1af-11ea-936d-c7b562419dfc.gif)

|  |  |

# 📋 QA

- Pledge to a Reward no Reward -> Update that pledge -> Change payment method for that pledge
- Pledge to a Digital Reward -> Update that pledge -> Change payment method for that pledge
- Pledge to a Reward with limited shipping -> Update that pledge -> Change payment method for that pledge
- Pledge to a Reward with unrestricted shipping -> Update that pledge -> Change payment method for that pledge

- Pledge to a Digital Reward + AddOns -> Update that pledge -> Change payment method for that pledge
- Pledge to a Reward with limited shipping + AddOns -> Update that pledge -> Change payment method for that pledge
- Pledge to a Reward with unrestricted shipping + AddOns -> Update that pledge -> Change payment method for that pledge

# Story 📖

[NT-1344](https://kickstarter.atlassian.net/browse/NT-1344)
[NT-1399](https://kickstarter.atlassian.net/browse/NT-1399)
[NT-1453](https://kickstarter.atlassian.net/browse/NT-1453)

2020-09-08 23:25 UTC, jgsamudio commented
Don't know if this is a known issue, but when I select the no reward option for the one inch straw project, I noticed that the default is 1 MX where it should be 10 MX. When I increment the bonus support it increments it by 10 instead of by 1

2020-09-08 23:34 UTC, jgsamudio requested changes

2020-09-08 23:34 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
> +                    .filter { it.reward()?.let { rw -> !RewardUtils.isNoReward(rw) }?: false }
```suggestion
                    .filter { it.reward()?.let { rw -> !RewardUtils.isNoReward(rw) } ?: false }
```

2020-09-08 23:34 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
> +            val shippingAmountWhenBacking = Observable.combineLatest(this.shippingRule, pledgeReason, backingShippingAmount, rewardAndAddOns) {rule, reason, bShippingAmount, listRw ->
```suggestion
            val shippingAmountWhenBacking = Observable.combineLatest(this.shippingRule, pledgeReason, backingShippingAmount, rewardAndAddOns) { rule, reason, bShippingAmount, listRw ->
```

2020-09-08 23:34 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
> +            val shippingAmountNewPledge = Observable.combineLatest(this.shippingRule, newPledge, rewardAndAddOns) {rule, reason, listRw ->
```suggestion
            val shippingAmountNewPledge = Observable.combineLatest(this.shippingRule, newPledge, rewardAndAddOns) { rule, reason, listRw ->
```

2020-09-08 23:34 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
> +                    .map { it }
```suggestion
```

2020-09-08 23:34 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
> +                    .map { it }
```suggestion
```

2020-09-08 23:34 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
> +                    .map { it }
No need for this line as its mapping to itself

2020-09-08 23:38 UTC, jgsamudio commented
When selecting a reward in the "one inch straw" project, I noticed that the rewards headers scrolls because the price is moved to a multiple line. Is this related to this PR or should we create a ticket for this?

![Screen Shot 2020-09-08 at 7 27 10 PM](https://user-images.githubusercontent.com/4837246/92537604-813bdc00-f20a-11ea-9330-102dfa62d0a2.png)

2020-09-10 15:12 UTC, Arkariang commented
> Don't know if this is a known issue, but when I select the no reward option for the one inch straw project, I noticed that the default is 1 MX where it should be 10 MX. When I increment the bonus support it increments it by 10 instead of by 1

Will be done here https://kickstarter.atlassian.net/browse/NT-1516

2020-09-10 15:12 UTC, Arkariang commented
> When selecting a reward in the "one inch straw" project, I noticed that the rewards headers scrolls because the price is moved to a multiple line. Is this related to this PR or should we create a ticket for this?
> 
> ![Screen Shot 2020-09-08 at 7 27 10 PM](https://user-images.githubusercontent.com/4837246/92537604-813bdc00-f20a-11ea-9330-102dfa62d0a2.png)

will be done here https://kickstarter.atlassian.net/browse/NT-1512

2020-09-10 19:30 UTC, jgsamudio approved these changes

2020-09-10 19:51 UTC, merged