NT-1442: Android Display an error state if add-ons fail to load
kickstarter/android-oss pull request #980
Opened 2020-09-14 21:05 UTC by leighdouglas

# 📲 What

Show an error alert dialog when there is an error retrieving the add-ons. Also allow user to tap retry to resend the networks calls to get the add-ons. 

# 🤔 Why

To give user more context on why add-ons are not loading correctly. 

# 🛠 How

Created a new stream that triggers the dialog when the network response is an error. Retry button resends the project data and reason to make a network call.

# 👀 See

![Screenshot_1600117077](https://user-images.githubusercontent.com/19390326/93137594-b97c6800-f6ab-11ea-8e2c-ddd89d04bb4f.png)

# 📋 QA

- Search for the project "one inch straw"
- Select "back project"
- Turn off wifi or put phone in airplane mode
- Select a pledge with add-ons
- Wait to see the error dialog
- Turn on wifi or turn off airplane mode
- Press "retry"
- After network call finishes, should show add-ons

# Story 📖

[NT-1442](https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=NT&modal=detail&selectedIssue=NT-1442&assignee=5efe5a70e0043f0bacaf7706&assignee=5eda9c57222d4d0b8296577e)

2020-09-16 21:28 UTC, jgsamudio requested changes

2020-09-16 21:28 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
> +import android.util.Log
Remove log if not needed

2020-09-16 21:28 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
> +                    .setPositiveButton("                     ${getString(R.string.Retry)}") { _, _ ->
Is there a way of setting the text of the positive and negative buttons without the front space?

2020-09-16 21:28 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
> +import android.util.Log
Remove log if not needed

2020-09-16 21:28 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
> +        /**Envoked when the retry button on the addOn Error alert dialog is pressed */
```suggestion
        /** Invoked when the retry button on the add-on Error alert dialog is pressed */
```

2020-09-16 21:28 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
> +        /**Emits an alert dialog when add-ons request results in error **/
```suggestion
        /** Emits an alert dialog when add-ons request results in error **/
```

2020-09-16 21:28 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
> +                    .filter { it.second == PledgeReason.PLEDGE }
Why was this added?

2020-09-17 17:11 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
> +                    .setPositiveButton("                     ${getString(R.string.Retry)}") { _, _ ->
This is the way that we set them so that they stack on top of one another as opposed to next to one another. Not sure there is another way to do this unless we create a custom layout for this alert dialog.

2020-09-17 17:14 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
> +import android.util.Log
👍

2020-09-17 17:14 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
> +import android.util.Log
👍

2020-09-17 17:44 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
> +                    .filter { it.second == PledgeReason.PLEDGE }
Removed

2020-09-17 19:22 UTC, jgsamudio commented on app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
> +                    .setPositiveButton("                     ${getString(R.string.Retry)}") { _, _ ->
I found this stack overflow article 
https://stackoverflow.com/questions/35880320/how-to-stack-alertdialog-buttons-vertically
and I agree with it, we shouldn't add spaces since the OS can change this. What happens if on a Galaxy phone the spaces don't look right? 

There's an example of a custom layout. What do you think about implementing that custom layout? The alert is simple. A text and 2 buttons.

2020-09-17 21:25 UTC, leighdouglas commented on app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
> +                    .setPositiveButton("                     ${getString(R.string.Retry)}") { _, _ ->
Will resolve in subsequent PR

2020-09-17 22:49 UTC, jgsamudio reviewed
I noticed that it takes a long time to present when the internet is off. It could be because of the behaviour / publish subject issue that we saw before? Can you verify this?

2020-09-18 15:56 UTC, leighdouglas commented
@jgsamudio When putting it in airplane mode on the virtual device, the error dialog popped up immediately. I then tested this behavior by turning off my wifi and the error dialog took longer to popup - consistent with your comment. I tested this with both `BehaviorSubject` and `PublishSubject`, and both behaved the same.

2020-09-18 16:31 UTC, jgsamudio approved these changes

2020-09-18 17:46 UTC, merged